
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "nfs-delete"
  hostAliases: []
  # - ip: 192.168.137.2
  #   hostnames:
  #   - example.com

namespace: "gitea"


replicaCount: 1


strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: "100%"
    maxUnavailable: 0

clusterDomain: cluster.local

image:
  registry: "docker.gitea.com"
  repository: gitea
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent
  rootless: true
  fullOverride: ""


ingress:
  enabled: true
  className: nginx
  className:
  annotations:
  hosts:
    - host: git.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - git.example.com

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

persistence:
  enabled: true
  create: true
  mount: true
  claimName: nginx
  size: 5Gi
  accessModes:
    - ReadWriteOnce
  labels: {}
  storageClass: nfs-delete
  subPath:
  volumeName: ""
  annotations:
    helm.sh/resource-policy: keep

gitea:
  admin:
    # existingSecret: gitea-admin-secret
    existingSecret:
    username: gitea_admin
    password: r8sA8CPHD9!bt6d
    email: "gitea@local.domain"
    passwordMode: keepUpdated


redis-cluster:
  enabled: false
  usePassword: false
  cluster:
    nodes: 3 # default: 6
    replicas: 0 # default: 1


redis:
  enabled: true
  architecture: standalone
  global:
    redis:
      password: changeme
  master:
    count: 1


postgresql-ha:
  global:
    postgresql:
      database: gitea
      password: gitea
      username: gitea
  enabled: false
  postgresql:
    repmgrPassword: changeme2
    postgresPassword: changeme1
    password: changeme4
  pgpool:
    adminPassword: changeme3
  service:
    ports:
      postgresql: 5432
  persistence:
    size: 10Gi

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password: gitea
        database: gitea
        username: gitea
      service:
        ports:
          postgresql: 5432
  primary:
    persistence:
      size: 5Gi


checkDeprecation: true
test:
  enabled: true
  image:
    name: busybox
    tag: latest

extraDeploy: []
